;; author.clj -- kami-genre-base-systems / rhythm, scene authoring.
;; Faithful reskin of kami-clj-play/games/survivors/author.clj (ADR-0036).
;;   clojure -M author.clj

(require '[datalevin.core :as d]
         '[clojure.pprint :as pp])

(def schema
  {:profile/tag   {:db/valueType :db.type/string  :db/unique :db.unique/identity}
   :profile/r     {:db/valueType :db.type/double}
   :profile/g     {:db/valueType :db.type/double}
   :profile/b     {:db/valueType :db.type/double}
   :profile/size  {:db/valueType :db.type/double}
   :profile/glow  {:db/valueType :db.type/double}
   :profile/pulse {:db/valueType :db.type/boolean}})

(def profiles
  [{:profile/tag "player" :profile/r 0.45 :profile/g 0.78 :profile/b 1.0  :profile/size 0.045 :profile/glow 0.70 :profile/pulse true}
   {:profile/tag "target" :profile/r 1.0  :profile/g 0.85 :profile/b 0.30 :profile/size 0.030 :profile/glow 0.45 :profile/pulse false}
   {:profile/tag "beat-spark" :profile/r 0.96 :profile/g 0.97 :profile/b 0.97 :profile/size 0.014 :profile/glow 0.90 :profile/pulse true}])

(def world {:player-speed 240.0 :camera-scale 620.0 :arena 460.0})
(def background {:top [0.05 0.05 0.09] :bottom [0.10 0.06 0.14] :grid 80.0})
(def burst {:count 8 :speed 140.0 :life 0.5 :color [1.0 0.85 0.30] :size 0.012})

(def db-dir (str (System/getProperty "user.dir") "/.datalevin"))

(defn -main []
  (let [conn (d/get-conn db-dir schema)]
    (d/clear conn)
    (let [conn (d/get-conn db-dir schema)]
      (d/transact! conn profiles)
      (let [rows (d/q '[:find ?tag ?r ?g ?b ?size ?glow ?pulse
                        :where
                        [?e :profile/tag ?tag]
                        [?e :profile/r ?r] [?e :profile/g ?g] [?e :profile/b ?b]
                        [?e :profile/size ?size] [?e :profile/glow ?glow]
                        [?e :profile/pulse ?pulse]]
                      (d/db conn))
            prof-map (into (sorted-map)
                           (for [[tag r g b size glow pulse] rows]
                             [(keyword tag)
                              (cond-> {:color [r g b] :size size :glow glow}
                                pulse (assoc :pulse true))]))
            scene {:game/id           :gftd.games/genre-base-rhythm
                   :game/title        "kami-genre-base-systems / rhythm"
                   :world             world
                   :render/profiles   prof-map
                   :render/background background
                   :fx/burst          burst}
            header (str ";; GENERATED by author.clj -- datalevin (Datalog) is the source of truth.\n"
                        ";; Edit author.clj data + re-run `clojure -M author.clj`; do not hand-edit.\n\n")]
        (spit "scene.edn" (str header (with-out-str (pp/pprint scene))))
        (d/close conn)
        (println (str "author: transacted " (count profiles) " profiles, wrote scene.edn"))))))

(-main)
