;; author.clj -- kami-genre-base-systems / post-apocalyptic, scene authoring.
;;   clojure -M author.clj
;;
;; NOTE: "post-apocalyptic" is a narrative/visual setting, not a distinct
;; core loop (see design/post-apocalyptic.edn) -- this is a real resource-
;; SCARCITY system layered on the single-player base: limited weapon
;; "charges" that deplete per use, forcing conservation/pacing. A genuine
;; scarcity-themed system, not a claim that the setting is inherently a
;; distinct archetype.

(require '[datalevin.core :as d]
         '[clojure.pprint :as pp])

(def schema
  {:profile/tag   {:db/valueType :db.type/string  :db/unique :db.unique/identity}
   :profile/r     {:db/valueType :db.type/double}
   :profile/g     {:db/valueType :db.type/double}
   :profile/b     {:db/valueType :db.type/double}
   :profile/size  {:db/valueType :db.type/double}
   :profile/glow  {:db/valueType :db.type/double}
   :profile/pulse {:db/valueType :db.type/boolean}})

(def profiles
  [{:profile/tag "player"  :profile/r 0.60 :profile/g 0.55 :profile/b 0.40 :profile/size 0.045 :profile/glow 0.55 :profile/pulse true}
   {:profile/tag "enemy"   :profile/r 0.70 :profile/g 0.30 :profile/b 0.25 :profile/size 0.030 :profile/glow 0.35 :profile/pulse false}
   {:profile/tag "salvage" :profile/r 0.85 :profile/g 0.70 :profile/b 0.30 :profile/size 0.025 :profile/glow 0.55 :profile/pulse true}])

(def world {:player-speed 220.0 :camera-scale 620.0 :arena 460.0})
(def background {:top [0.10 0.09 0.06] :bottom [0.16 0.13 0.09] :grid 80.0})
(def burst {:count 8 :speed 150.0 :life 0.5 :color [0.7 0.5 0.3] :size 0.012})

(def db-dir (str (System/getProperty "user.dir") "/.datalevin"))

(defn -main []
  (let [conn (d/get-conn db-dir schema)]
    (d/clear conn)
    (let [conn (d/get-conn db-dir schema)]
      (d/transact! conn profiles)
      (let [rows (d/q '[:find ?tag ?r ?g ?b ?size ?glow ?pulse
                        :where
                        [?e :profile/tag ?tag]
                        [?e :profile/r ?r] [?e :profile/g ?g] [?e :profile/b ?b]
                        [?e :profile/size ?size] [?e :profile/glow ?glow]
                        [?e :profile/pulse ?pulse]]
                      (d/db conn))
            prof-map (into (sorted-map)
                           (for [[tag r g b size glow pulse] rows]
                             [(keyword tag)
                              (cond-> {:color [r g b] :size size :glow glow}
                                pulse (assoc :pulse true))]))
            scene {:game/id           :gftd.games/genre-base-post-apocalyptic
                   :game/title        "kami-genre-base-systems / post-apocalyptic (scarcity preset)"
                   :world             world
                   :render/profiles   prof-map
                   :render/background background
                   :fx/burst          burst}
            header ";; GENERATED by author.clj -- do not hand-edit.\n\n"]
        (spit "scene.edn" (str header (with-out-str (pp/pprint scene))))
        (d/close conn)
        (println (str "author: transacted " (count profiles) " profiles, wrote scene.edn"))))))

(-main)
