;; author.clj -- kami-genre-base-systems / indie, scene authoring.
;;   clojure -M author.clj
;;
;; NOTE: "indie" is a publishing/production-scale category, not a gameplay
;; archetype (see design/indie.edn) -- this is a minimal experimental-
;; prototype SCAFFOLD: the smallest possible single-mechanic starter, fewer
;; constraints than any other base in this repo, meant as a genuinely
;; useful rapid-iteration kernel (matching how indie devs typically start
;; from a tiny loop and iterate), not a claim that "indie" is a mechanic.

(require '[datalevin.core :as d]
         '[clojure.pprint :as pp])

(def schema
  {:profile/tag   {:db/valueType :db.type/string  :db/unique :db.unique/identity}
   :profile/r     {:db/valueType :db.type/double}
   :profile/g     {:db/valueType :db.type/double}
   :profile/b     {:db/valueType :db.type/double}
   :profile/size  {:db/valueType :db.type/double}
   :profile/glow  {:db/valueType :db.type/double}
   :profile/pulse {:db/valueType :db.type/boolean}})

(def profiles
  [{:profile/tag "thing" :profile/r 0.90 :profile/g 0.90 :profile/b 0.95 :profile/size 0.040 :profile/glow 0.60 :profile/pulse true}])

(def world {:player-speed 200.0 :camera-scale 620.0 :arena 460.0})
(def background {:top [0.05 0.05 0.05] :bottom [0.10 0.10 0.10] :grid 100.0})
(def burst {:count 4 :speed 100.0 :life 0.3 :color [1.0 1.0 1.0] :size 0.010})

(def db-dir (str (System/getProperty "user.dir") "/.datalevin"))

(defn -main []
  (let [conn (d/get-conn db-dir schema)]
    (d/clear conn)
    (let [conn (d/get-conn db-dir schema)]
      (d/transact! conn profiles)
      (let [rows (d/q '[:find ?tag ?r ?g ?b ?size ?glow ?pulse
                        :where
                        [?e :profile/tag ?tag]
                        [?e :profile/r ?r] [?e :profile/g ?g] [?e :profile/b ?b]
                        [?e :profile/size ?size] [?e :profile/glow ?glow]
                        [?e :profile/pulse ?pulse]]
                      (d/db conn))
            prof-map (into (sorted-map)
                           (for [[tag r g b size glow pulse] rows]
                             [(keyword tag)
                              (cond-> {:color [r g b] :size size :glow glow}
                                pulse (assoc :pulse true))]))
            scene {:game/id           :gftd.games/genre-base-indie
                   :game/title        "kami-genre-base-systems / indie (minimal starter kernel)"
                   :world             world
                   :render/profiles   prof-map
                   :render/background background
                   :fx/burst          burst}
            header ";; GENERATED by author.clj -- do not hand-edit.\n\n"]
        (spit "scene.edn" (str header (with-out-str (pp/pprint scene))))
        (d/close conn)
        (println (str "author: transacted " (count profiles) " profiles, wrote scene.edn"))))))

(-main)
