;; author.clj -- kami-genre-base-systems / horror, scene authoring.
;;   clojure -M author.clj

(require '[datalevin.core :as d]
         '[clojure.pprint :as pp])

(def schema
  {:profile/tag   {:db/valueType :db.type/string  :db/unique :db.unique/identity}
   :profile/r     {:db/valueType :db.type/double}
   :profile/g     {:db/valueType :db.type/double}
   :profile/b     {:db/valueType :db.type/double}
   :profile/size  {:db/valueType :db.type/double}
   :profile/glow  {:db/valueType :db.type/double}
   :profile/pulse {:db/valueType :db.type/boolean}})

(def profiles
  [{:profile/tag "player"  :profile/r 0.55 :profile/g 0.55 :profile/b 0.60 :profile/size 0.040 :profile/glow 0.20 :profile/pulse false}
   {:profile/tag "threat"  :profile/r 0.60 :profile/g 0.05 :profile/b 0.10 :profile/size 0.038 :profile/glow 0.65 :profile/pulse true}
   {:profile/tag "scare"   :profile/r 0.95 :profile/g 0.05 :profile/b 0.05 :profile/size 0.055 :profile/glow 0.95 :profile/pulse true}])

(def world {:player-speed 190.0 :camera-scale 620.0 :arena 400.0})
(def background {:top [0.01 0.01 0.02] :bottom [0.03 0.02 0.04] :grid 80.0})
(def burst {:count 5 :speed 80.0 :life 0.3 :color [0.6 0.05 0.05] :size 0.010})

(def db-dir (str (System/getProperty "user.dir") "/.datalevin"))

(defn -main []
  (let [conn (d/get-conn db-dir schema)]
    (d/clear conn)
    (let [conn (d/get-conn db-dir schema)]
      (d/transact! conn profiles)
      (let [rows (d/q '[:find ?tag ?r ?g ?b ?size ?glow ?pulse
                        :where
                        [?e :profile/tag ?tag]
                        [?e :profile/r ?r] [?e :profile/g ?g] [?e :profile/b ?b]
                        [?e :profile/size ?size] [?e :profile/glow ?glow]
                        [?e :profile/pulse ?pulse]]
                      (d/db conn))
            prof-map (into (sorted-map)
                           (for [[tag r g b size glow pulse] rows]
                             [(keyword tag)
                              (cond-> {:color [r g b] :size size :glow glow}
                                pulse (assoc :pulse true))]))
            scene {:game/id           :gftd.games/genre-base-horror
                   :game/title        "kami-genre-base-systems / horror"
                   :world             world
                   :render/profiles   prof-map
                   :render/background background
                   :fx/burst          burst}
            header ";; GENERATED by author.clj -- do not hand-edit.\n\n"]
        (spit "scene.edn" (str header (with-out-str (pp/pprint scene))))
        (d/close conn)
        (println (str "author: transacted " (count profiles) " profiles, wrote scene.edn"))))))

(-main)
