;; author.clj -- kami-genre-base-systems / relaxing, scene authoring.
;;   clojure -M author.clj

(require '[datalevin.core :as d]
         '[clojure.pprint :as pp])

(def schema
  {:profile/tag   {:db/valueType :db.type/string  :db/unique :db.unique/identity}
   :profile/r     {:db/valueType :db.type/double}
   :profile/g     {:db/valueType :db.type/double}
   :profile/b     {:db/valueType :db.type/double}
   :profile/size  {:db/valueType :db.type/double}
   :profile/glow  {:db/valueType :db.type/double}
   :profile/pulse {:db/valueType :db.type/boolean}})

(def profiles
  [{:profile/tag "player"  :profile/r 0.60 :profile/g 0.85 :profile/b 0.75 :profile/size 0.045 :profile/glow 0.60 :profile/pulse true}
   {:profile/tag "dormant" :profile/r 0.45 :profile/g 0.50 :profile/b 0.40 :profile/size 0.028 :profile/glow 0.30 :profile/pulse false}
   {:profile/tag "grown"   :profile/r 0.55 :profile/g 0.90 :profile/b 0.45 :profile/size 0.038 :profile/glow 0.70 :profile/pulse true}])

(def world {:player-speed 160.0 :camera-scale 620.0 :arena 460.0})
(def background {:top [0.08 0.12 0.10] :bottom [0.14 0.18 0.14] :grid 80.0})
(def burst {:count 6 :speed 90.0 :life 0.8 :color [0.55 0.90 0.45] :size 0.010})

(def db-dir (str (System/getProperty "user.dir") "/.datalevin"))

(defn -main []
  (let [conn (d/get-conn db-dir schema)]
    (d/clear conn)
    (let [conn (d/get-conn db-dir schema)]
      (d/transact! conn profiles)
      (let [rows (d/q '[:find ?tag ?r ?g ?b ?size ?glow ?pulse
                        :where
                        [?e :profile/tag ?tag]
                        [?e :profile/r ?r] [?e :profile/g ?g] [?e :profile/b ?b]
                        [?e :profile/size ?size] [?e :profile/glow ?glow]
                        [?e :profile/pulse ?pulse]]
                      (d/db conn))
            prof-map (into (sorted-map)
                           (for [[tag r g b size glow pulse] rows]
                             [(keyword tag)
                              (cond-> {:color [r g b] :size size :glow glow}
                                pulse (assoc :pulse true))]))
            scene {:game/id           :gftd.games/genre-base-relaxing
                   :game/title        "kami-genre-base-systems / relaxing"
                   :world             world
                   :render/profiles   prof-map
                   :render/background background
                   :fx/burst          burst}
            header ";; GENERATED by author.clj -- do not hand-edit.\n\n"]
        (spit "scene.edn" (str header (with-out-str (pp/pprint scene))))
        (d/close conn)
        (println (str "author: transacted " (count profiles) " profiles, wrote scene.edn"))))))

(-main)
