;; author.clj -- kami-genre-base-systems / local-multiplayer, scene authoring.
;;   clojure -M author.clj

(require '[datalevin.core :as d]
         '[clojure.pprint :as pp])

(def schema
  {:profile/tag   {:db/valueType :db.type/string  :db/unique :db.unique/identity}
   :profile/r     {:db/valueType :db.type/double}
   :profile/g     {:db/valueType :db.type/double}
   :profile/b     {:db/valueType :db.type/double}
   :profile/size  {:db/valueType :db.type/double}
   :profile/glow  {:db/valueType :db.type/double}
   :profile/pulse {:db/valueType :db.type/boolean}})

(def profiles
  [{:profile/tag "p1"   :profile/r 0.45 :profile/g 0.78 :profile/b 1.0  :profile/size 0.045 :profile/glow 0.70 :profile/pulse true}
   {:profile/tag "p2-ai" :profile/r 1.0 :profile/g 0.60 :profile/b 0.30 :profile/size 0.045 :profile/glow 0.70 :profile/pulse true}
   {:profile/tag "ball" :profile/r 0.95 :profile/g 0.95 :profile/b 0.95 :profile/size 0.025 :profile/glow 0.80 :profile/pulse false}])

(def world {:player-speed 260.0 :camera-scale 620.0 :arena 460.0})
(def background {:top [0.06 0.10 0.07] :bottom [0.10 0.16 0.10] :grid 80.0})
(def burst {:count 8 :speed 160.0 :life 0.4 :color [0.95 0.95 0.95] :size 0.012})

(def db-dir (str (System/getProperty "user.dir") "/.datalevin"))

(defn -main []
  (let [conn (d/get-conn db-dir schema)]
    (d/clear conn)
    (let [conn (d/get-conn db-dir schema)]
      (d/transact! conn profiles)
      (let [rows (d/q '[:find ?tag ?r ?g ?b ?size ?glow ?pulse
                        :where
                        [?e :profile/tag ?tag]
                        [?e :profile/r ?r] [?e :profile/g ?g] [?e :profile/b ?b]
                        [?e :profile/size ?size] [?e :profile/glow ?glow]
                        [?e :profile/pulse ?pulse]]
                      (d/db conn))
            prof-map (into (sorted-map)
                           (for [[tag r g b size glow pulse] rows]
                             [(keyword tag)
                              (cond-> {:color [r g b] :size size :glow glow}
                                pulse (assoc :pulse true))]))
            scene {:game/id           :gftd.games/genre-base-local-multiplayer
                   :game/title        "kami-genre-base-systems / local-multiplayer"
                   :world             world
                   :render/profiles   prof-map
                   :render/background background
                   :fx/burst          burst}
            header ";; GENERATED by author.clj -- do not hand-edit.\n\n"]
        (spit "scene.edn" (str header (with-out-str (pp/pprint scene))))
        (d/close conn)
        (println (str "author: transacted " (count profiles) " profiles, wrote scene.edn"))))))

(-main)
