;; author.clj -- kami-genre-base-systems / kids-family, scene authoring.
;;   clojure -M author.clj

(require '[datalevin.core :as d]
         '[clojure.pprint :as pp])

(def schema
  {:profile/tag   {:db/valueType :db.type/string  :db/unique :db.unique/identity}
   :profile/r     {:db/valueType :db.type/double}
   :profile/g     {:db/valueType :db.type/double}
   :profile/b     {:db/valueType :db.type/double}
   :profile/size  {:db/valueType :db.type/double}
   :profile/glow  {:db/valueType :db.type/double}
   :profile/pulse {:db/valueType :db.type/boolean}})

(def profiles
  [{:profile/tag "player" :profile/r 0.55 :profile/g 0.80 :profile/b 1.0  :profile/size 0.050 :profile/glow 0.75 :profile/pulse true}
   {:profile/tag "treat"  :profile/r 1.0  :profile/g 0.75 :profile/b 0.35 :profile/size 0.030 :profile/glow 0.65 :profile/pulse true}])

(def world {:player-speed 200.0 :camera-scale 620.0 :arena 460.0})
(def background {:top [0.10 0.14 0.20] :bottom [0.18 0.20 0.28] :grid 80.0})
(def burst {:count 14 :speed 130.0 :life 0.5 :color [1.0 0.85 0.4] :size 0.014})

(def db-dir (str (System/getProperty "user.dir") "/.datalevin"))

(defn -main []
  (let [conn (d/get-conn db-dir schema)]
    (d/clear conn)
    (let [conn (d/get-conn db-dir schema)]
      (d/transact! conn profiles)
      (let [rows (d/q '[:find ?tag ?r ?g ?b ?size ?glow ?pulse
                        :where
                        [?e :profile/tag ?tag]
                        [?e :profile/r ?r] [?e :profile/g ?g] [?e :profile/b ?b]
                        [?e :profile/size ?size] [?e :profile/glow ?glow]
                        [?e :profile/pulse ?pulse]]
                      (d/db conn))
            prof-map (into (sorted-map)
                           (for [[tag r g b size glow pulse] rows]
                             [(keyword tag)
                              (cond-> {:color [r g b] :size size :glow glow}
                                pulse (assoc :pulse true))]))
            scene {:game/id           :gftd.games/genre-base-kids-family
                   :game/title        "kami-genre-base-systems / kids-family"
                   :world             world
                   :render/profiles   prof-map
                   :render/background background
                   :fx/burst          burst}
            header ";; GENERATED by author.clj -- do not hand-edit.\n\n"]
        (spit "scene.edn" (str header (with-out-str (pp/pprint scene))))
        (d/close conn)
        (println (str "author: transacted " (count profiles) " profiles, wrote scene.edn"))))))

(-main)
